// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of grace period check
 */
export type GracePeriodStatus = { 
/**
 * Whether the grace period is still valid
 */
isValid: boolean, 
/**
 * Days remaining in grace period (0 if expired)
 */
daysRemaining: bigint, 
/**
 * Whether the license has ever been verified online
 */
hasBeenVerified: boolean, 
/**
 * Unix timestamp when grace period ends
 */
gracePeriodEndsAt: bigint, };
