// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicensePlan } from "./LicensePlan";

/**
 * License cache entity for offline grace period support
 * Stored in SQLite as a single-row table (id = 1)
 */
export type LicenseCache = { 
/**
 * Plan type: free or pro
 */
plan: LicensePlan, 
/**
 * Unix timestamp of last successful verification
 */
last_verified_at: bigint, 
/**
 * Unix timestamp when license expires (None for lifetime)
 */
expires_at: bigint | null, 
/**
 * Unix timestamp when grace period ends (last_verified_at + 7 days)
 */
grace_period_ends_at: bigint, };
