// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LicenseData = { licenseKey: string, plan: string, status: string, isValid: boolean, activatedAt: string | null, expiresAt: string | null, };
