// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tauri event payloads
 */
export type LicenseVerifiedEvent = { plan: string, expiresAt: bigint | null, };
