// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicensePlan } from "./LicensePlan";

/**
 * Complete license status for the frontend
 */
export type LicenseStatus = { 
/**
 * Current license plan
 */
plan: LicensePlan, 
/**
 * Whether the license has been verified at least once
 */
isVerified: boolean, 
/**
 * Unix timestamp of last successful verification (0 if never)
 */
lastVerifiedAt: bigint, 
/**
 * Unix timestamp when grace period ends
 */
gracePeriodEndsAt: bigint, 
/**
 * Unix timestamp when license expires (null for lifetime)
 */
expiresAt: bigint | null, 
/**
 * Whether the grace period is currently valid
 */
isGracePeriodValid: boolean, 
/**
 * Days remaining in grace period
 */
daysUntilGraceExpires: bigint, 
/**
 * Whether the license subscription is expired
 */
isLicenseExpired: boolean, 
/**
 * Whether app functionality should be blocked
 */
isBlocked: boolean, };
