// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicenseData } from "./LicenseData";
import type { LicenseErrorData } from "./LicenseErrorData";

/**
 * License verification response from backend API
 */
export type LicenseVerifyResponse = { success: boolean, data: LicenseData | null, error: LicenseErrorData | null, };
