// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedeemEarlyAdopterDataResult } from "./RedeemEarlyAdopterDataResult";
import type { RedeemEarlyAdopterError } from "./RedeemEarlyAdopterError";

/**
 * Result type for redeem early adopter code command
 */
export type RedeemEarlyAdopterResult = { success: boolean, data: RedeemEarlyAdopterDataResult | null, error: RedeemEarlyAdopterError | null, };
