// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicensePlan } from "./LicensePlan";

/**
 * Result of online license verification
 */
export type VerifyLicenseResult = { isValid: boolean, plan: LicensePlan, expiresAt: bigint | null, error: string | null, };
