pub mod get_video_info;
pub mod import_video;
pub mod save_transcript;
pub mod selection_use_cases;
pub mod generate_cuts;
pub mod segment_video;
pub mod validate_segments;
pub mod prepare_preview;
pub mod export_video;
pub mod verify_license_online;
pub mod check_grace_period;
pub mod update_license_cache;
pub mod get_license_status;
pub mod check_for_update;
pub mod download_update;
pub mod backup_current_version;
pub mod restore_backup;
pub mod cleanup_old_backups;
pub mod project_state_use_cases;

// Used in future stories
#[allow(unused_imports)]
pub use get_video_info::GetVideoInfoUseCase;
pub use import_video::ImportVideoUseCase;
pub use save_transcript::SaveTranscriptUseCase;
pub use selection_use_cases::{SaveSelectionsUseCase, GetSelectionsUseCase, ClearSelectionsUseCase};
pub use generate_cuts::GenerateCutsUseCase;
pub use segment_video::SegmentVideoUseCase;
pub use validate_segments::ValidateSegmentsUseCase;
pub use prepare_preview::PreparePreviewUseCase;
pub use export_video::ExportVideoUseCase;
pub use verify_license_online::{VerifyLicenseOnlineUseCase, VerifyLicenseResult};
pub use check_grace_period::{CheckGracePeriodUseCase, GracePeriodStatus};
pub use update_license_cache::UpdateLicenseCacheUseCase;
pub use get_license_status::{GetLicenseStatusUseCase, LicenseStatus};
pub use check_for_update::{CheckForUpdateUseCase, CheckUpdateResult};
pub use download_update::{DownloadUpdateUseCase, DownloadUpdateResult};
pub use backup_current_version::{BackupCurrentVersionUseCase, BackupInfo};
pub use restore_backup::RestoreBackupUseCase;
pub use cleanup_old_backups::CleanupOldBackupsUseCase;
pub use project_state_use_cases::{SaveProjectStateUseCase, LoadProjectStateUseCase, MarkCleanShutdownUseCase, CheckDirtyShutdownUseCase, ResetCleanShutdownUseCase};
